// <auto-generated />
using System;
using GIIS_lab2.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GIIS_lab2.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220926171558_initbd")]
    partial class initbd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Address");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("327d90ac-9247-4f29-8231-c9650d499ba4"),
                            Address = "Kolotushkino",
                            Name = "Alex"
                        },
                        new
                        {
                            Id = new Guid("214f5fc6-a34f-4e25-8d7e-9ffe1f0da122"),
                            Address = "Bombass",
                            Name = "Dranik"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
